In [1]:
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer

import pandas as pd
import numpy as np

In [2]:
paragraph = """I have three visions for India. In 3000 years of our history, people from all over 
               the world have come and invaded us, captured our lands, conquered our minds. 
               From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,
               the French, the Dutch, all of them came and looted us, took over what was ours. 
               Yet we have not done this to any other nation. We have not conquered anyone. 
               We have not grabbed their land, their culture, 
               their history and tried to enforce our way of life on them. 
               Why? Because we respect the freedom of others.That is why my 
               first vision is that of freedom. I believe that India got its first vision of 
               this in 1857, when we started the War of Independence. It is this freedom that
               we must protect and nurture and build on. If we are not free, no one will respect us.
               My second vision for India’s development. For fifty years we have been a developing nation.
               It is time we see ourselves as a developed nation. We are among the top 5 nations of the world
               in terms of GDP. We have a 10 percent growth rate in most areas. Our poverty levels are falling.
               Our achievements are being globally recognised today. Yet we lack the self-confidence to
               see ourselves as a developed nation, self-reliant and self-assured. Isn’t this incorrect?
               I have a third vision. India must stand up to the world. Because I believe that unless India 
               stands up to the world, no one will respect us. Only strength respects strength. We must be 
               strong not only as a military power but also as an economic power. Both must go hand-in-hand. 
               My good fortune was to have worked with three great minds. Dr. Vikram Sarabhai of the Dept. of 
               space, Professor Satish Dhawan, who succeeded him and Dr. Brahm Prakash, father of nuclear material.
               I was lucky to have worked with all three of them closely and consider this the great opportunity of my life. 
               I see four milestones in my career"""

In [3]:
sentences = nltk.sent_tokenize(paragraph)
sentences[:3]

['I have three visions for India.',
 'In 3000 years of our history, people from all over \n               the world have come and invaded us, captured our lands, conquered our minds.',
 'From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,\n               the French, the Dutch, all of them came and looted us, took over what was ours.']

In [4]:
nltk.word_tokenize(sentences[0])

['I', 'have', 'three', 'visions', 'for', 'India', '.']

In [5]:
ps = PorterStemmer()
lemm = WordNetLemmatizer()

In [6]:
corpus = []
for i in range(len(sentences)):
    review = re.sub('[^a-zA-Z]', ' ', sentences[i])
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in set(
        stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

In [7]:
corpus [:3]

['three vision india',
 'year histori peopl world come invad us captur land conquer mind',
 'alexand onward greek turk mogul portugues british french dutch came loot us took']

In [8]:
sentences[:3]

['I have three visions for India.',
 'In 3000 years of our history, people from all over \n               the world have come and invaded us, captured our lands, conquered our minds.',
 'From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,\n               the French, the Dutch, all of them came and looted us, took over what was ours.']

In [9]:
all_words = []

for sentence in corpus:
    for each_word in sentence.split():
        all_words.append(each_word)   

In [10]:
all_words_freq = nltk.FreqDist(all_words)
print(list(all_words_freq.keys())[-10:])
print(list(all_words_freq.values())[-10:])
print(len(all_words_freq))

['father', 'nuclear', 'materi', 'lucki', 'close', 'consid', 'opportun', 'four', 'mileston', 'career']
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
113


In [11]:
from collections import Counter, OrderedDict
counter = Counter()
for line in corpus:
    counter.update(line.split())
    
sorted_by_freq_tuples = sorted(
    counter.items(), key=lambda x: x[1], reverse=True)
ordered_dict = OrderedDict(sorted_by_freq_tuples)

In [12]:
len(ordered_dict)

113

In [13]:
import tensorflow
import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [14]:
# Initialize the Tokenizer class
# total number of words in word_index
tokenizer = Tokenizer(num_words=100, oov_token="<OOV>")
tokenizer

In [15]:
# Generate indices for each word in the corpus
tokenizer.fit_on_texts(corpus)
# Get the indices and print it
word_index = tokenizer.word_index
print(word_index)
vocab_size = len(word_index)
print(vocab_size)

{'<OOV>': 1, 'vision': 2, 'india': 3, 'nation': 4, 'world': 5, 'us': 6, 'respect': 7, 'must': 8, 'develop': 9, 'three': 10, 'freedom': 11, 'see': 12, 'self': 13, 'year': 14, 'histori': 15, 'land': 16, 'conquer': 17, 'mind': 18, 'yet': 19, 'life': 20, 'first': 21, 'believ': 22, 'one': 23, 'stand': 24, 'strength': 25, 'power': 26, 'hand': 27, 'work': 28, 'great': 29, 'dr': 30, 'peopl': 31, 'come': 32, 'invad': 33, 'captur': 34, 'alexand': 35, 'onward': 36, 'greek': 37, 'turk': 38, 'mogul': 39, 'portugues': 40, 'british': 41, 'french': 42, 'dutch': 43, 'came': 44, 'loot': 45, 'took': 46, 'done': 47, 'anyon': 48, 'grab': 49, 'cultur': 50, 'tri': 51, 'enforc': 52, 'way': 53, 'other': 54, 'got': 55, 'start': 56, 'war': 57, 'independ': 58, 'protect': 59, 'nurtur': 60, 'build': 61, 'free': 62, 'second': 63, 'fifti': 64, 'time': 65, 'among': 66, 'top': 67, 'term': 68, 'gdp': 69, 'percent': 70, 'growth': 71, 'rate': 72, 'area': 73, 'poverti': 74, 'level': 75, 'fall': 76, 'achiev': 77, 'global': 

In [21]:
sequences = tokenizer.texts_to_sequences(corpus)

In [22]:
max_len = 0
for each_sequence in sequences:
    seq_len = len(each_sequence)
    if seq_len > max_len:
        max_len = seq_len

print(max_len)

13


In [23]:
# Pad the sequences to a uniform length
padded = pad_sequences(sequences, maxlen=max_len,
                       padding='post', truncating='post')
print(padded[:2])

[[10  2  3  0  0  0  0  0  0  0  0  0  0]
 [14 15 31  5 32 33  6 34 16 17 18  0  0]]


In [24]:
padded.shape

(31, 13)

In [25]:
X = padded.copy()
y = np.random.randint(0, 2,padded.shape[0])
print(len(y))

31


In [26]:
y

array([1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0])

In [27]:
vocab_size=114
embeded_vector_size = 5

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size,
          input_length=max_len, name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [28]:
vocab_size

114

In [29]:
model.compile(optimizer='adam', loss='binary_crossentropy',
              metrics=['accuracy'])
print(model.summary())


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 13, 5)             570       
                                                                 
 flatten (Flatten)           (None, 65)                0         
                                                                 
 dense (Dense)               (None, 1)                 66        
                                                                 
Total params: 636 (2.48 KB)
Trainable params: 636 (2.48 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [31]:
model.fit(X, y, epochs=50, verbose=0)

In [32]:
# evaluate the model
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 206ms/step - loss: 0.6018 - accuracy: 0.9032


0.9032257795333862

In [33]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

114

In [35]:
vocab_size

114

In [37]:
print(word_index)

{'<OOV>': 1, 'vision': 2, 'india': 3, 'nation': 4, 'world': 5, 'us': 6, 'respect': 7, 'must': 8, 'develop': 9, 'three': 10, 'freedom': 11, 'see': 12, 'self': 13, 'year': 14, 'histori': 15, 'land': 16, 'conquer': 17, 'mind': 18, 'yet': 19, 'life': 20, 'first': 21, 'believ': 22, 'one': 23, 'stand': 24, 'strength': 25, 'power': 26, 'hand': 27, 'work': 28, 'great': 29, 'dr': 30, 'peopl': 31, 'come': 32, 'invad': 33, 'captur': 34, 'alexand': 35, 'onward': 36, 'greek': 37, 'turk': 38, 'mogul': 39, 'portugues': 40, 'british': 41, 'french': 42, 'dutch': 43, 'came': 44, 'loot': 45, 'took': 46, 'done': 47, 'anyon': 48, 'grab': 49, 'cultur': 50, 'tri': 51, 'enforc': 52, 'way': 53, 'other': 54, 'got': 55, 'start': 56, 'war': 57, 'independ': 58, 'protect': 59, 'nurtur': 60, 'build': 61, 'free': 62, 'second': 63, 'fifti': 64, 'time': 65, 'among': 66, 'top': 67, 'term': 68, 'gdp': 69, 'percent': 70, 'growth': 71, 'rate': 72, 'area': 73, 'poverti': 74, 'level': 75, 'fall': 76, 'achiev': 77, 'global': 

In [46]:
weights[77]

array([ 0.02206156,  0.05499516, -0.00827639, -0.06139808, -0.08980474],
      dtype=float32)

In [45]:
weights[4]

array([-0.09396591,  0.04655337,  0.0732692 ,  0.03466852, -0.07482236],
      dtype=float32)