In [14]:
import tensorflow as tf
import numpy as np
import sys
from  sys import getsizeof

In [26]:
tf.random.set_seed(5)
print("Random values")
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))

print("\nConstant values")
print(tf.constant(4), tf.constant("I am Vikram"), tf.constant([True,False]))
print(tf.constant([4,3,2],dtype="int8"))

Random values
tf.Tensor([4 3 1], shape=(3,), dtype=int32)

Constant values
tf.Tensor(4, shape=(), dtype=int32) tf.Tensor(b'I am Vikram', shape=(), dtype=string) tf.Tensor([ True False], shape=(2,), dtype=bool)
tf.Tensor([4 3 2], shape=(3,), dtype=int8)


In [39]:
tf_2d = tf.constant(
    [[1,2,3],
    [1,2,3],
     [1,2,3]],
    dtype="float32",
)
print(tf_2d,"\n",tf_2d.shape)

tf.Tensor(
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]], shape=(3, 3), dtype=float32) 
 (3, 3)


In [42]:
np_array = np.array([1,2,3])
print(np_array)
tf_array = tf.convert_to_tensor(np_array, dtype="float32")
tf_array_2 = tf.convert_to_tensor(np_array, dtype=tf.float32)
print(tf_array)
print(tf_array_2)

[1 2 3]
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)


In [77]:
tf.eye(num_rows=2,num_columns=2,batch_shape=[2,3], dtype=tf.dtypes.float32)

<tf.Tensor: shape=(2, 3, 2, 2), dtype=float32, numpy=
array([[[[1., 0.],
         [0., 1.]],

        [[1., 0.],
         [0., 1.]],

        [[1., 0.],
         [0., 1.]]],


       [[[1., 0.],
         [0., 1.]],

        [[1., 0.],
         [0., 1.]],

        [[1., 0.],
         [0., 1.]]]], dtype=float32)>

In [76]:
tf.fill([2,3,2,4],1.5)

<tf.Tensor: shape=(2, 3, 2, 4), dtype=float32, numpy=
array([[[[1.5, 1.5, 1.5, 1.5],
         [1.5, 1.5, 1.5, 1.5]],

        [[1.5, 1.5, 1.5, 1.5],
         [1.5, 1.5, 1.5, 1.5]],

        [[1.5, 1.5, 1.5, 1.5],
         [1.5, 1.5, 1.5, 1.5]]],


       [[[1.5, 1.5, 1.5, 1.5],
         [1.5, 1.5, 1.5, 1.5]],

        [[1.5, 1.5, 1.5, 1.5],
         [1.5, 1.5, 1.5, 1.5]],

        [[1.5, 1.5, 1.5, 1.5],
         [1.5, 1.5, 1.5, 1.5]]]], dtype=float32)>

In [79]:
tf.ones_like(tf.fill([2, 3,2,4],1.5))
tf.zeros_like(tf.fill([2, 3,2,4],1.5))

<tf.Tensor: shape=(2, 3, 2, 4), dtype=float32, numpy=
array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]]], dtype=float32)>

In [75]:
tf.zeros([2,3,2,5])
tf.ones([2, 3,2,5])

<tf.Tensor: shape=(2, 3, 2, 5), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]], dtype=float32)>

In [85]:
tf.random.uniform([2,2],minval=3,maxval=10, dtype=tf.dtypes.int32)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 7],
       [9, 9]])>

In [86]:
tf.random.normal([2,5],mean=0, stddev=1, dtype=tf.dtypes.float32)

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[ 1.4665463e+00, -1.0248139e+00,  8.6743289e-01, -2.2424309e+00,
         8.9757569e-02],
       [-1.1256858e-01, -1.6262239e-01, -3.1064131e-04, -2.0654018e+00,
         9.5980637e-02]], dtype=float32)>

In [21]:
import tensorflow as tf
import sys

# Create TensorFlow constant tensors with different ranges
tensor1 = tf.constant([x for x in range(100)])
tensor2 = tf.constant([x for x in range(5, 150)])

# Get the sizes of the tensors
size1 = sys.getsizeof(tensor1.numpy())
size2 = sys.getsizeof(tensor2.numpy())

print(f"Size of tensor1: {size1} bytes")
print(f"Size of tensor2: {size2} bytes")

Size of tensor1: 512 bytes
Size of tensor2: 692 bytes
