In [1]:
import tensorflow as tf
import numpy as np
import sys
from  sys import getsizeof

In [3]:
tf_arr = tf.fill([2,2,2,4],2.7)

In [4]:
tf_arr.shape

TensorShape([2, 2, 2, 4])

In [5]:
tf_arr = tf.constant([[2, 20, 30, 3, 6],
             [3, 11, 16, 1, 8],
             [14, 45, 23, 5, 27]])
tf.math.argmax(tf_arr,axis=1)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([2, 2, 1], dtype=int64)>

In [36]:
tf_arr1 = tf.constant([[1,2,3],
                       [4,5,6]])
tf_arr2 = tf.constant([1,1,1])

print(tf_arr1.shape, tf_arr2.shape, tf.expand_dims(tf_arr2, axis=1).shape)

print(tf.matmul(tf_arr1, tf.expand_dims(tf_arr2, axis=1)))
print(tf.linalg.matmul(tf_arr1, tf.expand_dims(tf_arr2, axis=1)))

(2, 3) (3,) (3, 1)
tf.Tensor(
[[ 6]
 [15]], shape=(2, 1), dtype=int32)
tf.Tensor(
[[ 6]
 [15]], shape=(2, 1), dtype=int32)


In [38]:
tf_arr_expdm  = tf.expand_dims(tf_arr1,axis=2)
tf_arr_expdm

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])>

In [51]:
tf.expand_dims(tf.constant([1,2,3,5]),axis=-1)

<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [5]])>

In [52]:
tf.expand_dims(tf.constant([[1, 2, 3,5],
                            [4,5,6,7]]),axis=-1)

<tf.Tensor: shape=(2, 4, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3],
        [5]],

       [[4],
        [5],
        [6],
        [7]]])>

In [39]:
tf.squeeze(tf_arr_expdm,axis=2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [40]:
tf.reshape(tf_arr_expdm,shape=[2,3])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [43]:
tf_arr_pad = tf.constant([[1,2,3],
                          [2,4,5]])
tf_to_pad = tf.constant([[1,2],
                         [6,5]])